### ISSUE TITLE
Hope to support vue-validitor!

### ISSUE THREAD

**Issue by muei** [appcomponents/material-components#21]

**Comment by mariaczi** [comment]
It's a shame really. This lib is so nice and I am glad to use it, but it is impossible to use it with vue-validator at all... 

@mjanzs are you going to do something with that? Any idea?

**Comment by mjanzs** [comment]
I looked at it, but it is seems to be really impossible to simply integrate vue-validator with components, because validator binds directly form fields which are basically wrapped by components.

So it can't be easily used from over e.g. `md-input` component and place it into component is very invasive solution. I have to think about it. Also every idea are welcome. I don't know how to do that at this moment.

**Comment by mariaczi** [comment]
Maybe passing vue-validator body as md-input prop and passing that to `<input>` inside component?

**Comment by mjanzs** [comment]
Yes, I've got that idea too, but still it isn't easy to manage it. It will require more changes

**Comment by mariaczi** [comment]
Any progress? Generally it is really hard to get any validation with that currently.
Would be really nice to have possibility to use `vue-validator` or (maybe would be easier, idk) 'vue-form` https://github.com/fergaldoyle/vue-form ?
It is something MUST HAVE as client side validation is crucial.

**Comment by mjanzs** [comment]
Inputs have `valid` property also success and error message. You can validate value yourself.

I've started with some kind of integration with validator.
It is based on passing `input` as a slot.

I should look like 
```
<md-field :success-msg="successMsg"
                :error-msg="errorMsg"
                :valid="$validation.data.valid"
                :dirty="$validation.data.dirty"
                class="col s6">
                    <span slot="label">First Name</span>
                    <input v-model="data" v-validate:data="{ required: true, minlength: 8 }"/>
                </md-field>
```

But with it you are completely losing all `<md-input>` features because component isn't aware about state of input.
Second think is that I had problems with scope of validator object in slots.

**Comment by mariaczi** [comment]
@mjanzs Making input as slot is not good idea to be honest.

What is the issue to do it that way `<md-field validator-rules="{ required: true, minlength: 8 }">` and then populate it into input inside component with `<input v-validate:{fieldName}="{ validator-rules}">`
Maybe my question is silly but I did not go so deep into that complicated reusable components design.

**Comment by mjanzs** [comment]
I wanted to avoid any external dependency in components. I'll have look at it, not sure if is it possible to use variable in directive (v-validate:{fieldName}).

**Comment by mariaczi** [comment]
Anyone sorted it out?
I have no forms validation in my project so far which is really bad...

**Comment by muei** [comment]
Close it. `material-components` is not update and `vue-validitor` is idle
